// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gating_gtMethod
Rcpp::List gating_gtMethod(Rcpp::S4 x, Rcpp::S4 y, Rcpp::S4 gtPop, Rcpp::String parent, Rcpp::List pp_res);
RcppExport SEXP openCyto_gating_gtMethod(SEXP xSEXP, SEXP ySEXP, SEXP gtPopSEXP, SEXP parentSEXP, SEXP pp_resSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::S4 >::type x(xSEXP );
        Rcpp::traits::input_parameter< Rcpp::S4 >::type y(ySEXP );
        Rcpp::traits::input_parameter< Rcpp::S4 >::type gtPop(gtPopSEXP );
        Rcpp::traits::input_parameter< Rcpp::String >::type parent(parentSEXP );
        Rcpp::traits::input_parameter< Rcpp::List >::type pp_res(pp_resSEXP );
        Rcpp::List __result = gating_gtMethod(x, y, gtPop, parent, pp_res);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// collapseData
NumericMatrix collapseData(List mat_list, StringVector colnames);
RcppExport SEXP openCyto_collapseData(SEXP mat_listSEXP, SEXP colnamesSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< List >::type mat_list(mat_listSEXP );
        Rcpp::traits::input_parameter< StringVector >::type colnames(colnamesSEXP );
        NumericMatrix __result = collapseData(mat_list, colnames);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
